---
deployment:
  tasks:
    - export DEPLOYWEB=/home/rentingcom/public_html/web/
    - /bin/rsync -av web/dist/ $DEPLOYWEB
    - export DEPLOYADMIN=/home/rentingcom/public_html/admin/
    - /bin/rsync -av admin/dist/ $DEPLOYADMIN